language: node_js

node_js:
  - "node"

script: 
  - yarn
  - yarn bootstrap
  - yarn lint
  - yarn build
  - yarn test

before_deploy:
  - "npm i -g makeshift && makeshift -s @bloomberg -r registry.npmjs.org"
  - "cd packages/record-tuple-polyfill"
deploy:
  provider: npm
  email: ossbuild@bloomberg.net
  api_key: $NPM_TOKEN
  skip_cleanup: true
  on:
    tags: true
    node: "node"
    condition: -n "$NPM_TOKEN"
after_deploy:
  - "cd ../../"
